name: PR Branch MASTER to BUGFIX

on:
  push:
    branches:
      - "master"

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: pull-request-master-to-bugfix
      if: ${{ github.repository == 'RodrigoSMarques/flutter_branch_sdk' }}
      uses: repo-sync/pull-request@v2.6.2
      with:
        source_branch: "master"                           
        destination_branch: "bugfix"              
        pr_title: "PR Branch MASTER into BUGFIX"
        pr_body: "ðŸ‘‘ *An automated PR*"              
        pr_label: "auto-pr"                          
        pr_draft: false                              
        pr_allow_empty: false                        
        github_token: ${{ secrets.GITHUB_TOKEN }}
